/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mortgage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Calendar;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author prime
 */
public class alerts extends javax.swing.JFrame {

    
    String sno;
    String True="true";
    String Mod="yes";
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    /**
     * Creates new form alerts
     */
    public alerts() {
                 con=sql_connection.ConnectDB();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 35)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setRowHeight(38);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 1100, 570));

        jPanel2.setBackground(new java.awt.Color(204, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label1.setText("Alerts !");
        jPanel2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 560, 80));

        button1.setBackground(new java.awt.Color(204, 255, 204));
        button1.setFont(new java.awt.Font("Lucida Sans", 1, 42)); // NOI18N
        button1.setForeground(new java.awt.Color(102, 0, 102));
        button1.setLabel("Show");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 710, 250, 60));

        button2.setBackground(new java.awt.Color(204, 255, 153));
        button2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        button2.setLabel("Go back");
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked

        new welcome().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_button2MouseClicked

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
      // TODO add your handling code here:
      Date_difference();
      
      
      ///showing alerts
      try{
        String sql="Select  serial , name , amount , date from lent where alerts='True' ";
        pst=con.prepareStatement(sql);
        rs=pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
       }
       
       catch(Exception e)
       {
         
           
           JOptionPane.showMessageDialog(null, e);
       
           
       }
      
      
      
    }//GEN-LAST:event_button1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alerts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alerts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alerts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alerts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alerts().setVisible(true);
            }
        });
    }

    
    
  
        public void Date_difference()
    {
        
  //      int day_difference=0;
        int i=1;        ///Starting point
        
        
        DateTimeFormatter formatter=DateTimeFormatter.ofPattern("dd/MM/yyyy");
         
        //1 st date
             String current_date = new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime());
           LocalDate system_date =LocalDate.parse(current_date,formatter);
          
        
        String db_date="";
         
              
         
         //getting max serial
         
         try{
            String serial_query="select max(serial) from lent";
            pst=con.prepareStatement(serial_query);
             rs=pst.executeQuery();    
             sno=rs.getString("max(serial)");
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
         
         
         //getting date from tabel
         while(i<=Integer.valueOf(sno))
         {
             LocalDate database_date =LocalDate.parse(date_extractor(i),formatter);
             
             long daysBetween=ChronoUnit.DAYS.between(database_date, system_date);
             
             
             
             if(daysBetween<10)
             {
                  
                 String SQL="update  lent set alerts='True' where serial ='"+i+"' ";
                 
             try{
           
           pst=con.prepareStatement(SQL);
            
             pst.execute();
             System.out.println(daysBetween);
             
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
                 
             }
             
             else
             {
                 String SQL="update  lent set alerts='False' where serial ='"+i+"' ";
                 
                 try{
           
           pst=con.prepareStatement(SQL);
            
             pst.execute();
             System.out.println(daysBetween);
             
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
                 System.out.println("else");
                 
             }
             i++;
             
         }
        
         
         
    }
      
    
    
    
    
 public String date_extractor(int serial)
{
    
     int s=serial;
     String extracted_date="";
    try {
             String test="Select reminder from lent where serial='"+s+"'";
            pst=con.prepareStatement(test);
             rs=pst.executeQuery();
             
             if(rs.next())
             {
                 extracted_date=rs.getString("reminder");
                 
              
             }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    
    
    
    return extracted_date;
    
    
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
