/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mortgage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author prime
 */
public class changes extends javax.swing.JFrame {
    
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
   
 
    
    


    /**
     * Creates new form changes
     */
    public changes() {
                
        
        
        con=sql_connection.ConnectDB();
        
        

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        textField1 = new java.awt.TextField();
        label3 = new java.awt.Label();
        dater1 = new java.awt.Label();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        label4 = new java.awt.Label();
        dater2 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        button4 = new java.awt.Button();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        dater3 = new java.awt.Label();
        label9 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        button5 = new java.awt.Button();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        button6 = new java.awt.Button();
        dater4 = new java.awt.Label();
        label11 = new java.awt.Label();
        textField9 = new java.awt.TextField();
        button7 = new java.awt.Button();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        label12 = new java.awt.Label();
        dater5 = new java.awt.Label();
        jSeparator10 = new javax.swing.JSeparator();
        textField10 = new java.awt.TextField();
        button8 = new java.awt.Button();
        label14 = new java.awt.Label();
        jSeparator11 = new javax.swing.JSeparator();
        dater6 = new java.awt.Label();
        textField13 = new java.awt.TextField();
        button9 = new java.awt.Button();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        label16 = new java.awt.Label();
        textField14 = new java.awt.TextField();
        button10 = new java.awt.Button();
        button11 = new java.awt.Button();
        button12 = new java.awt.Button();
        button13 = new java.awt.Button();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jDateChooser5 = new com.toedter.calendar.JDateChooser();
        jDateChooser6 = new com.toedter.calendar.JDateChooser();
        jDateChooser7 = new com.toedter.calendar.JDateChooser();
        label6 = new java.awt.Label();
        serial_field = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(153, 255, 0));
        label1.setFont(new java.awt.Font("Cambria Math", 0, 36)); // NOI18N
        label1.setText("Update / Modification Page");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 80));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textField1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel3.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 240, 40));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Palatino Linotype", 1, 29)); // NOI18N
        label3.setForeground(new java.awt.Color(51, 0, 0));
        label3.setText("Returned Amount");
        jPanel3.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 270, 50));

        dater1.setAlignment(java.awt.Label.CENTER);
        dater1.setFont(new java.awt.Font("Palatino Linotype", 1, 29)); // NOI18N
        dater1.setForeground(new java.awt.Color(51, 0, 0));
        dater1.setText("Date");
        jPanel3.add(dater1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 260, 40));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 50, 260));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 600, 10));

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setFont(new java.awt.Font("Palatino Linotype", 1, 29)); // NOI18N
        label4.setForeground(new java.awt.Color(51, 0, 0));
        label4.setText("Returned Amount");
        jPanel3.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 260, 50));

        dater2.setAlignment(java.awt.Label.CENTER);
        dater2.setFont(new java.awt.Font("Palatino Linotype", 1, 29)); // NOI18N
        dater2.setForeground(new java.awt.Color(51, 0, 0));
        dater2.setText("Date");
        jPanel3.add(dater2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 260, 40));

        textField2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel3.add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 140, 240, 40));

        button4.setBackground(new java.awt.Color(153, 102, 255));
        button4.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        button4.setForeground(new java.awt.Color(255, 255, 255));
        button4.setLabel("Update");
        button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button4MouseClicked(evt);
            }
        });
        jPanel3.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 180, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, 20, 260));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 600, 10));

        dater3.setAlignment(java.awt.Label.CENTER);
        dater3.setFont(new java.awt.Font("Palatino Linotype", 1, 29)); // NOI18N
        dater3.setForeground(new java.awt.Color(51, 0, 0));
        dater3.setText("Date");
        jPanel3.add(dater3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 80, 220, 40));

        label9.setAlignment(java.awt.Label.CENTER);
        label9.setFont(new java.awt.Font("Palatino Linotype", 1, 29)); // NOI18N
        label9.setForeground(new java.awt.Color(51, 0, 0));
        label9.setText("Returned Amount");
        jPanel3.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 130, 270, 50));

        textField3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel3.add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 140, 240, 40));

        button5.setBackground(new java.awt.Color(153, 102, 255));
        button5.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        button5.setForeground(new java.awt.Color(255, 255, 255));
        button5.setLabel("Update");
        button5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button5MouseClicked(evt);
            }
        });
        jPanel3.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 190, 180, -1));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 270, 600, 10));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 10, 20, 260));

        button6.setBackground(new java.awt.Color(153, 102, 255));
        button6.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        button6.setForeground(new java.awt.Color(255, 255, 255));
        button6.setLabel("Update");
        button6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button6MouseClicked(evt);
            }
        });
        jPanel3.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, 180, -1));

        dater4.setAlignment(java.awt.Label.CENTER);
        dater4.setFont(new java.awt.Font("Palatino Linotype", 1, 29)); // NOI18N
        dater4.setForeground(new java.awt.Color(51, 0, 0));
        dater4.setText("Date");
        jPanel3.add(dater4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 260, 40));

        label11.setAlignment(java.awt.Label.CENTER);
        label11.setFont(new java.awt.Font("Palatino Linotype", 1, 29)); // NOI18N
        label11.setForeground(new java.awt.Color(51, 0, 0));
        label11.setText("Returned Amount");
        jPanel3.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 270, 50));

        textField9.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel3.add(textField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 240, 40));

        button7.setBackground(new java.awt.Color(153, 102, 255));
        button7.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        button7.setForeground(new java.awt.Color(255, 255, 255));
        button7.setLabel("Update");
        button7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button7MouseClicked(evt);
            }
        });
        jPanel3.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 180, -1));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 600, 10));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 50, 260));

        label12.setAlignment(java.awt.Label.CENTER);
        label12.setFont(new java.awt.Font("Palatino Linotype", 1, 29)); // NOI18N
        label12.setForeground(new java.awt.Color(51, 0, 0));
        label12.setText("Returned Amount");
        jPanel3.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 260, 50));

        dater5.setAlignment(java.awt.Label.CENTER);
        dater5.setFont(new java.awt.Font("Palatino Linotype", 1, 29)); // NOI18N
        dater5.setForeground(new java.awt.Color(51, 0, 0));
        dater5.setText("Date");
        jPanel3.add(dater5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 260, 40));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 600, 10));

        textField10.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel3.add(textField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 400, 240, 40));

        button8.setBackground(new java.awt.Color(153, 102, 255));
        button8.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        button8.setForeground(new java.awt.Color(255, 255, 255));
        button8.setLabel("Update");
        button8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button8MouseClicked(evt);
            }
        });
        jPanel3.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, 180, -1));

        label14.setAlignment(java.awt.Label.CENTER);
        label14.setFont(new java.awt.Font("Palatino Linotype", 1, 29)); // NOI18N
        label14.setForeground(new java.awt.Color(51, 0, 0));
        label14.setText("Returned Amount");
        jPanel3.add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 360, 270, 50));

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 270, 20, 260));

        dater6.setAlignment(java.awt.Label.CENTER);
        dater6.setFont(new java.awt.Font("Palatino Linotype", 1, 29)); // NOI18N
        dater6.setForeground(new java.awt.Color(51, 0, 0));
        dater6.setText("Date");
        jPanel3.add(dater6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 300, 220, 40));

        textField13.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel3.add(textField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 370, 240, 40));

        button9.setBackground(new java.awt.Color(153, 102, 255));
        button9.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        button9.setForeground(new java.awt.Color(255, 255, 255));
        button9.setLabel("First update");
        button9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button9MouseClicked(evt);
            }
        });
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        jPanel3.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 630, 300, 50));
        jPanel3.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 530, 600, 10));

        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 270, 20, 260));

        label16.setAlignment(java.awt.Label.CENTER);
        label16.setFont(new java.awt.Font("Palatino Linotype", 1, 29)); // NOI18N
        label16.setForeground(new java.awt.Color(51, 0, 0));
        label16.setText("Comment");
        jPanel3.add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 430, 220, 40));

        textField14.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel3.add(textField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 430, 240, 40));

        button10.setBackground(new java.awt.Color(153, 102, 255));
        button10.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        button10.setForeground(new java.awt.Color(255, 255, 255));
        button10.setLabel("Update");
        button10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button10MouseClicked(evt);
            }
        });
        jPanel3.add(button10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 480, 180, -1));

        button11.setBackground(new java.awt.Color(153, 102, 255));
        button11.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        button11.setForeground(new java.awt.Color(255, 255, 255));
        button11.setLabel("First update");
        button11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button11MouseClicked(evt);
            }
        });
        jPanel3.add(button11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 630, 300, 50));

        button12.setBackground(new java.awt.Color(153, 102, 255));
        button12.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        button12.setForeground(new java.awt.Color(255, 255, 255));
        button12.setLabel("First update");
        button12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button12MouseClicked(evt);
            }
        });
        jPanel3.add(button12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 300, 50));

        button13.setBackground(new java.awt.Color(153, 102, 255));
        button13.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        button13.setForeground(new java.awt.Color(255, 255, 255));
        button13.setLabel("First update");
        button13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button13MouseClicked(evt);
            }
        });
        jPanel3.add(button13, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 630, 300, 50));

        jDateChooser2.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser2.setDateFormatString("dd/MM/yyyy");
        jPanel3.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 80, 240, 40));

        jDateChooser3.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser3.setDateFormatString("dd/MM/yyyy");
        jPanel3.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 310, 240, 40));

        jDateChooser4.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser4.setDateFormatString("dd/MM/yyyy");
        jPanel3.add(jDateChooser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 240, 40));

        jDateChooser5.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser5.setDateFormatString("dd/MM/yyyy");
        jPanel3.add(jDateChooser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 240, 40));

        jDateChooser6.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser6.setDateFormatString("dd/MM/yyyy");
        jPanel3.add(jDateChooser6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 240, 40));

        jDateChooser7.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser7.setDateFormatString("dd/MM/yyyy");
        jPanel3.add(jDateChooser7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, 240, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1820, 770));

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setBackground(new java.awt.Color(153, 255, 0));
        label6.setFont(new java.awt.Font("Palatino Linotype", 1, 29)); // NOI18N
        label6.setForeground(new java.awt.Color(51, 0, 0));
        label6.setText("Serial Number");
        jPanel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 25, 210, 60));

        serial_field.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        serial_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serial_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(serial_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 160, 50));

        button1.setBackground(new java.awt.Color(153, 255, 0));
        button1.setFont(new java.awt.Font("Javanese Text", 1, 20)); // NOI18N
        button1.setLabel("Go back");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 30, 220, 40));

        button2.setBackground(new java.awt.Color(153, 255, 0));
        button2.setFont(new java.awt.Font("Javanese Text", 1, 20)); // NOI18N
        button2.setLabel("Find");
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
        });
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 30, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1840, 910));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked

        new welcome().setVisible(true);
                super.dispose();  
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseClicked

    private void serial_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serial_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serial_fieldActionPerformed

    private void button4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseClicked
       
        
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
            String date = sdf.format(jDateChooser5.getDate());
            
        String SQL="update  lent set date_r1='"+date+"' , ra_r1='"+textField1.getText()+"'  where serial ='"+serial_field.getText()+"' ";
                 
             try{
           
           pst=con.prepareStatement(SQL);
            
             pst.execute();
            
             
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
    }//GEN-LAST:event_button4MouseClicked

    private void button5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseClicked
     
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
            String date = sdf.format(jDateChooser2.getDate());
            
        String SQL="update  lent set date_r3='"+date+"' , ra_r3='"+textField3.getText()+"'  where serial ='"+serial_field.getText()+"' ";
                 
             try{
           
           pst=con.prepareStatement(SQL);
            
             pst.execute();
            
             
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
        
        
    }//GEN-LAST:event_button5MouseClicked

    private void button6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MouseClicked
  
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
            String date = sdf.format(jDateChooser4.getDate());
            
        String SQL="update  lent set date_r2='"+date+"' , ra_r2='"+textField2.getText()+"'  where serial ='"+serial_field.getText()+"' ";
                 
             try{
           
           pst=con.prepareStatement(SQL);
            
             pst.execute();
            
             
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
    }//GEN-LAST:event_button6MouseClicked

    private void button7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MouseClicked

        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
            String date = sdf.format(jDateChooser6.getDate());
            
        String SQL="update  lent set date_r4='"+date+"' , ra_r4='"+textField9.getText()+"'  where serial ='"+serial_field.getText()+"' ";
                 
             try{
           
           pst=con.prepareStatement(SQL);
            
             pst.execute();
            
             
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
        
    }//GEN-LAST:event_button7MouseClicked

    private void button8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button8MouseClicked
      
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
            String date = sdf.format(jDateChooser7.getDate());
            
        String SQL="update  lent set date_r5='"+date+"' , ra_r5='"+textField10.getText()+"'  where serial ='"+serial_field.getText()+"' ";
                 
             try{
           
           pst=con.prepareStatement(SQL);
            
             pst.execute();
            
             
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
        
    }//GEN-LAST:event_button8MouseClicked

    private void button9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button9MouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button10MouseClicked
      // TODO add your handling code here:
        
        
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
            String date = sdf.format(jDateChooser3.getDate());
            
        String SQL="update  lent set date_r6='"+date+"' , ra_r6='"+textField13.getText()+"' , return_comment='"+textField14.getText()+"'  where serial ='"+serial_field.getText()+"' ";
                 
             try{
           
           pst=con.prepareStatement(SQL);
            
             pst.execute();
            
             
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
        
    }//GEN-LAST:event_button10MouseClicked

    private void button11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button11MouseClicked

    private void button12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button12MouseClicked

    private void button13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button13MouseClicked

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button9ActionPerformed

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked
        // TODO add your handling code here:
        r1();
        r2();
        r3();
        r4();
        r5();
        r6();
        
        
        
        /////amount
        ra1();
        ra2();
        ra3();
        ra4();
        ra5();
        ra6();
    }//GEN-LAST:event_button2MouseClicked

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    
    
    
    
    public Date initial() throws ParseException
    {
        
    SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
     String  init_date="01/01/1996";
    Date converted = sdf.parse(init_date);
    return converted;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changes().setVisible(true);
            }
        });
}
    public void r1()
    {
        
        
         try {
            
             String test="Select date_r1 from lent where serial=?";
             
             pst=con.prepareStatement(test);
                    pst.setString(1, serial_field.getText());
                    rs=pst.executeQuery();
                    System.out.println("done");
                    
             if(rs.next())
             {
                 
                 System.out.println("ok");
                 
                 
                 
                 SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
                 
                 String date_r1=rs.getString("date_r1");
                 
                 
                 
                 if(date_r1==null)
                      jDateChooser5.setDate(initial());
                 else
                 {
                     
                 
                 Date convertedCurrentDate = sdf.parse(date_r1);
                 
                 jDateChooser5.setDate(convertedCurrentDate);
                 
                 }
                 
                 
              
             }
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
    
        
       
        
    }
    
    
     public void r2()
    {
        
         try {
            
             String test="Select date_r2 from lent where serial=?";
             
             pst=con.prepareStatement(test);
                    pst.setString(1, serial_field.getText());
                    rs=pst.executeQuery();
                    System.out.println("okay");
                    
             if(rs.next())
             {
                 
                 System.out.println("okayy");
                 
                 
                 
                 SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
                 
                 String date_r2=rs.getString("date_r2");
                 
                 
                 
                 if(date_r2==null)
                      jDateChooser4.setDate(initial());
                 else
                 {
                     
                     
                 
                 Date convertedCurrentDate = sdf.parse(date_r2);
                 
                 jDateChooser4.setDate(convertedCurrentDate);
                 
                 }
                 
                 
              
             }
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
    
        
       
        
    }
     
     
     
     
      public void r3()
    {
        
         try {
            
             String test="Select date_r3 from lent where serial=?";
             
             pst=con.prepareStatement(test);
                    pst.setString(1, serial_field.getText());
                    rs=pst.executeQuery();
                 
                    
             if(rs.next())
             {
                 
                 
                 SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
                 
                 String date_r3=rs.getString("date_r3");
                 
                 
                 
                 if(date_r3==null)
                      jDateChooser2.setDate(initial());
                 else
                 {
                     
                     
                 
                 Date convertedCurrentDate = sdf.parse(date_r3);
                 
                 jDateChooser2.setDate(convertedCurrentDate);
                 
                 }
                 
                 
              
             }
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
    
        
       
        
    }
      
          public void r4()
    {
        
         try {
            
             String test="Select date_r4 from lent where serial=?";
             
             pst=con.prepareStatement(test);
                    pst.setString(1, serial_field.getText());
                    rs=pst.executeQuery();
                 
                    
             if(rs.next())
             {
                 
                 
                 SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
                 
                 String date_r4=rs.getString("date_r4");
                 
                 
                 
                 if(date_r4==null)
                      jDateChooser6.setDate(initial());
                 else
                 {
                     
                     
                 
                 Date convertedCurrentDate = sdf.parse(date_r4);
                 
                 jDateChooser6.setDate(convertedCurrentDate);
                 
                 }
                 
                 
              
             }
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
    
        
       
        
    }
          
          
              public void r5()
    {
        
         try {
            
             String test="Select date_r5 from lent where serial=?";
             
             pst=con.prepareStatement(test);
                    pst.setString(1, serial_field.getText());
                    rs=pst.executeQuery();
                 
                    
             if(rs.next())
             {
                 
                 
                 SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
                 
                 String date_r5=rs.getString("date_r5");
                 
                 
                 
                 if(date_r5==null)
                      jDateChooser7.setDate(initial());
                 else
                 {
                     
                     
                 
                 Date convertedCurrentDate = sdf.parse(date_r5);
                 
                 jDateChooser7.setDate(convertedCurrentDate);
                 
                 }
                 
                 
              
             }
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
    
        
       
        
    }
              
              
              
                  public void r6()
    {
        
         try {
            
             String test="Select date_r6 from lent where serial=?";
             
             pst=con.prepareStatement(test);
                    pst.setString(1, serial_field.getText());
                    rs=pst.executeQuery();
                 
                    
             if(rs.next())
             {
                 
                 
                 SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
                 
                 String date_r6=rs.getString("date_r6");
                 
                 
                 
                 if(date_r6==null)
                      jDateChooser3.setDate(initial());
                 else
                 {
                     
                     
                 
                 Date convertedCurrentDate = sdf.parse(date_r6);
                 
                 jDateChooser3.setDate(convertedCurrentDate);
                 
                 }
                 
                 
              
             }
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
    
        
       
        
    }
    
    
////////////////////////////////////////////AMOUNT
                  
     public void ra1()
    {
        
        
         try {
            
             String test="Select ra_r1 from lent where serial=?";
             
             pst=con.prepareStatement(test);
                    pst.setString(1, serial_field.getText());
                    rs=pst.executeQuery();
                    
             if(rs.next())
             {
                 String ra_r1=rs.getString("ra_r1");
                 
                 
                 
                 if(ra_r1==null)
                 {
                      textField1.setText("");
               
                 }
                 else
                 {
                    
                 textField1.setText(ra_r1);
                 
                 }
                 
                 
              
             }
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
    
        
       
        
    }
     
     
          public void ra2()
    {
        
        
         try {
            
             String test="Select ra_r2 from lent where serial=?";
             
             pst=con.prepareStatement(test);
                    pst.setString(1, serial_field.getText());
                    rs=pst.executeQuery();
                    
             if(rs.next())
             {
                 String ra_r2=rs.getString("ra_r2");
                 
                 
                 
                 if(ra_r2==null)
                 {
                      textField2.setText("");
                      
               
                 }
                 else
                 {
                    
                 textField2.setText(ra_r2);
                 
                 }
                 
                 
              
             }
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
    
        
       
        
    }
     
    public void ra3()
    {
        
        
         try {
            
             String test="Select ra_r3 from lent where serial=?";
             
             pst=con.prepareStatement(test);
                    pst.setString(1, serial_field.getText());
                    rs=pst.executeQuery();
                    
             if(rs.next())
             {
                 String ra_r3=rs.getString("ra_r3");
                 
                 
                 
                 if(ra_r3==null)
                 {
                      textField3.setText("");
               
                 }
                 else
                 {
                    
                 textField3.setText(ra_r3);
                 
                 }
                 
                 
              
             }
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
    
        
       
        
    }
    
    public void ra4()
    {
        
        
         try {
            
             String test="Select ra_r4 from lent where serial=?";
             
             pst=con.prepareStatement(test);
                    pst.setString(1, serial_field.getText());
                    rs=pst.executeQuery();
                    
             if(rs.next())
             {
                 String ra_r4=rs.getString("ra_r4");
                 
                 
                 
                 if(ra_r4==null)
                 {
                      textField9.setText("");
               
                 }
                 else
                 {
                    
                 textField9.setText(ra_r4);
                 
                 }
                 
                 
              
             }
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
      
        
    }
    
    
    public void ra5()
    {
        
        
         try {
            
             String test="Select ra_r5 from lent where serial=?";
             
             pst=con.prepareStatement(test);
                    pst.setString(1, serial_field.getText());
                    rs=pst.executeQuery();
                    
             if(rs.next())
             {
                 String ra_r5=rs.getString("ra_r5");
                 
                 
                 
                 if(ra_r5==null)
                 {
                      textField10.setText("");
               
                 }
                 else
                 {
                    
                 textField10.setText(ra_r5);
                 
                 }
                 
                 
              
             }
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
      
        
    }
    
    public void ra6()
    {
        
        
         try {
            
             String test="Select ra_r6 from lent where serial=?";
             
             pst=con.prepareStatement(test);
                    pst.setString(1, serial_field.getText());
                    rs=pst.executeQuery();
                    
             if(rs.next())
             {
                 String ra_r6=rs.getString("ra_r6");
                 
                 
                 
                 if(ra_r6==null)
                 {
                      textField13.setText("");
               
                 }
                 else
                 {
                    
                 textField13.setText(ra_r6);
                 
                 }
                 
                 
              
             }
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
      
        
    }
    
                  
                  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button10;
    private java.awt.Button button11;
    private java.awt.Button button12;
    private java.awt.Button button13;
    private java.awt.Button button2;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private java.awt.Label dater1;
    private java.awt.Label dater2;
    private java.awt.Label dater3;
    private java.awt.Label dater4;
    private java.awt.Label dater5;
    private java.awt.Label dater6;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private com.toedter.calendar.JDateChooser jDateChooser6;
    private com.toedter.calendar.JDateChooser jDateChooser7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private java.awt.Label label1;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label14;
    private java.awt.Label label16;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label6;
    private java.awt.Label label9;
    private java.awt.TextField serial_field;
    private java.awt.TextField textField1;
    private java.awt.TextField textField10;
    private java.awt.TextField textField13;
    private java.awt.TextField textField14;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField9;
    // End of variables declaration//GEN-END:variables
}
