/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mortgage;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Calendar;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author prime
 */
public class home extends javax.swing.JFrame {
    
    
    String sno;
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
     public static final String FONT_PATH="fonts/Kruti Dev 714 Normal.ttf";
    private static Font createFont(String url) throws FontFormatException, IOException
    {
        return Font.createFont(Font.TRUETYPE_FONT, home.class.getClassLoader().getResourceAsStream(FONT_PATH))
                .deriveFont(20 ,30f);
    }
    String selected;
    
    
   

    /**
     * Creates new form home
     */
    public home() {
        con=sql_connection.ConnectDB();
        initComponents();
        
        
        
        
        try
        {
            Font mangal=createFont("mangal.ttf");
            jLabel20.setFont(mangal);
             jLabel23.setFont(mangal);
             jLabel13.setFont(mangal);
             jLabel15.setFont(mangal);
             jLabel14.setFont(mangal);
             jLabel19.setFont(mangal);
             jLabel21.setFont(mangal);
             jLabel18.setFont(mangal);
           
            

                        
        }
        
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e);
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button2 = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        serial_no = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ri = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        purity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        item = new java.awt.TextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        mno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 200, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 8, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 51, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 0, 32)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Reminders");
        jPanel4.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 50));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 280, 50));

        jTable1.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setRowHeight(35);
        jTable1.setRowMargin(2);
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 670, 720));

        button2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        button2.setLabel("Show");
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
        });
        jPanel3.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 810, 190, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 690, 870));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(0, 204, 204));
        jLabel12.setFont(new java.awt.Font("Courier New", 1, 23)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Serial Number");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 30));

        serial_no.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        serial_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serial_noActionPerformed(evt);
            }
        });
        jPanel5.add(serial_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 150, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 360, 50));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 0, 204));
        label2.setText("Signature");
        jPanel2.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 710, 140, 30));

        jLabel23.setBackground(new java.awt.Color(204, 255, 204));
        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel23.setText("uke");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 110, 30));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel1.setText("Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 130, 30));

        name.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 180, 30));

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel5.setText("Date");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 100, 30));

        jLabel20.setBackground(new java.awt.Color(204, 255, 204));
        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel20.setText("izkfIr fnukd");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 160, 30));

        jDateChooser2.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 180, 30));

        jLabel10.setBackground(new java.awt.Color(204, 255, 204));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel10.setText("Amount");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, -1));

        jLabel13.setBackground(new java.awt.Color(204, 255, 204));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel13.setText("jde");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 100, 30));

        amount.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountKeyTyped(evt);
            }
        });
        jPanel2.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 180, 30));

        jLabel8.setBackground(new java.awt.Color(204, 255, 204));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel8.setText("Rate of interest");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 190, -1));

        jLabel15.setBackground(new java.awt.Color(204, 255, 204));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel15.setText("C;kt dk nj");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 190, -1));

        ri.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        ri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                riKeyTyped(evt);
            }
        });
        jPanel2.add(ri, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 180, 30));

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel2.setText("Interest Type");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 160, 30));

        jLabel14.setBackground(new java.awt.Color(204, 255, 204));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel14.setText("C;kt dk izdkj");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 160, 30));

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CI", "SI", " " }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel2.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 180, 30));

        jLabel9.setBackground(new java.awt.Color(204, 255, 204));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel9.setText("Purity");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 160, 30));

        jLabel19.setBackground(new java.awt.Color(204, 255, 204));
        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel19.setText("'kq)rk");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 160, 30));

        purity.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        purity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                purityKeyTyped(evt);
            }
        });
        jPanel2.add(purity, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 180, 30));

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel3.setText("Item");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 160, 30));

        jLabel18.setBackground(new java.awt.Color(204, 255, 204));
        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel18.setText("ux");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 590, 160, 30));
        jPanel2.add(item, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 590, 200, 120));

        jLabel11.setBackground(new java.awt.Color(204, 255, 204));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel11.setText("Mobile Number");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 160, 30));

        jLabel21.setBackground(new java.awt.Color(204, 255, 204));
        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel21.setText("eksckby uEcj");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 160, 30));

        mno.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        mno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mnoKeyTyped(evt);
            }
        });
        jPanel2.add(mno, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 180, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 990, 770));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Reminder");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 800, 150, 30));

        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 800, 190, 30));

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("Add");
        jButton6.setFocusCycleRoot(true);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 870, 160, 60));

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Go back");
        jButton7.setFocusCycleRoot(true);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 870, 160, 60));

        jButton8.setBackground(new java.awt.Color(204, 204, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("Print");
        jButton8.setFocusCycleRoot(true);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 870, 160, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1780, 960));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked
        // TODO add your handling code here:

        Date_difference();

        ///showing alerts
        try{
            String sql="Select  serial , name , date from lent where alerts='True' ";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        }

        catch(Exception e)
        {

            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_button2MouseClicked

    private void serial_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serial_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serial_noActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void amountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_amountKeyReleased

    private void amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_amountKeyTyped

    private void riKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_riKeyTyped
       
    }//GEN-LAST:event_riKeyTyped

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:

        selected=type.getSelectedItem().toString();

    }//GEN-LAST:event_typeActionPerformed

    private void purityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purityKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_purityKeyTyped

    private void mnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_mnoKeyTyped

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked

        ////for serial
       
        
        try{
            String serial_query="select max(serial) from lent";
            pst=con.prepareStatement(serial_query);
             rs=pst.executeQuery();    
             sno=rs.getString("max(serial)");
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
       
        
        int serial_number=Integer.valueOf(sno);
        serial_number++;
        
        
        
        
        serial_no.setText(String.valueOf(serial_number));
        
      
        String SQL="insert into lent (serial , date , name , amount , rate , type , purity , item , mobile , reminder) VALUES(?,?,?,?,?,?,?,?,?,?)";
        
        try
        {
            pst=con.prepareStatement(SQL);
            
          
            pst.setString(1,String.valueOf(serial_number));
            
             SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
            String date = sdf.format(jDateChooser2.getDate());
            pst.setString(2,date);
            
            
            pst.setString(3,name.getText());
            pst.setString(4,amount.getText());
            pst.setString(5,ri.getText());
            pst.setString(6,(String)type.getSelectedItem());
            pst.setString(7,purity.getText());
            pst.setString(8,item.getText());
            pst.setString(9,mno.getText());
           
           
            String alert_date = sdf.format(jDateChooser1.getDate());
            pst.setString(10,alert_date);
            
           
            
            pst.execute();
            
            
            
            JOptionPane.showMessageDialog(null ,"Done !");
            
            
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        new welcome().setVisible(true);
                super.dispose();  
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:sd
        
        
        calling_for_print();
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }
    
    
    
    
    
        public void Date_difference()
    {
        
         //      int day_difference=0;
        int i=1;        ///Starting point
        
        
        DateTimeFormatter formatter=DateTimeFormatter.ofPattern("dd/MM/yyyy");
         
        //1 st date
             String current_date = new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime());
           LocalDate system_date =LocalDate.parse(current_date,formatter);
          
        
        String db_date="";
         
              
         
         //getting max serial
         
         try{
            String serial_query="select max(serial) from lent";
            pst=con.prepareStatement(serial_query);
             rs=pst.executeQuery();    
             sno=rs.getString("max(serial)");
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
         
         
         ///getting date from tabel
         while(i<=Integer.valueOf(sno))
         {
             LocalDate database_date =LocalDate.parse(date_extractor(i),formatter);
             
             long daysBetween=ChronoUnit.DAYS.between(database_date, system_date);
             
             
             
             if(daysBetween<10)
             {
                  
                 String SQL="update  lent set alerts='True' where serial ='"+i+"' ";
                 
             try{
           
           pst=con.prepareStatement(SQL);
            
             pst.execute();
             System.out.println(daysBetween);
             
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
                 
             }
             
             else
             {
                 String SQL="update  lent set alerts='False' where serial ='"+i+"' ";
                 
                 try{
           
           pst=con.prepareStatement(SQL);
            
             pst.execute();
             System.out.println(daysBetween);
             
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
                 System.out.println("else");
                 
             }
             i++;
             
         }
        
         
         
    }
    
    
    
    public String date_extractor(int serial)
{
    
     int s=serial;
     String extracted_date="";
    try {
             String test="Select reminder from lent where serial='"+s+"'";
            pst=con.prepareStatement(test);
             rs=pst.executeQuery();
             
             if(rs.next())
             {
                 extracted_date=rs.getString("reminder");
                 
              
             }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    
    
    
    return extracted_date;
    
    
}
    
    
       
       public void calling_for_print()
    {
         PrinterJob  job= PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        job.setPrintable(new Printable()
        {
            public int print(Graphics pg,PageFormat pf,int pageNum)
            {
                if (pageNum>0)
                    return Printable.NO_SUCH_PAGE;
            
            Graphics2D g2=(Graphics2D)pg;
            g2.translate(pf.getImageableX(),pf.getImageableY());
            
         //   g2.scale(0.465,0.555);
         g2.scale(0.465,0.75);
                   jPanel2.paint(g2);
//          
               
                return Printable.PAGE_EXISTS;
            }
        }
        );
        boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){}
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private java.awt.Button button2;
    private java.awt.TextArea item;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextField mno;
    private javax.swing.JTextField name;
    private javax.swing.JTextField purity;
    private javax.swing.JTextField ri;
    private javax.swing.JTextField serial_no;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
