package mortgage;


import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author prime
 */
public class interest_2dates extends javax.swing.JFrame {
    double p , r , t , si;

    /**
     * Creates new form interest_2dates
     */
    public interest_2dates() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        textField1 = new java.awt.TextField();
        jPanel2 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        button2 = new java.awt.Button();
        textField2 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 420, 50));

        jDateChooser2.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 420, 50));

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        jPanel1.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 220, 40));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        label1.setText("Interest Calculator");
        jPanel2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 120));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 690, 120));

        button2.setBackground(new java.awt.Color(0, 204, 204));
        button2.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        button2.setLabel("Calculate");
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 580, 150, 40));

        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        jPanel1.add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 220, 40));

        textField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField3ActionPerformed(evt);
            }
        });
        jPanel1.add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 640, 410, 40));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(0, 204, 204));
        label2.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        label2.setText("Rate");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 120, 40));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(0, 204, 204));
        label3.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        label3.setText("Principal");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked
        // TODO add your handling code here:
        
            double p , r ,t , si;
            p=Double.valueOf(textField1.getText());
            r=Double.valueOf(textField2.getText());
            t=days();
            si=(p*r*(t/365))/100;
            
            textField3.setText(String.valueOf(si));
            
    }//GEN-LAST:event_button2MouseClicked

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void textField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interest_2dates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interest_2dates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interest_2dates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interest_2dates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interest_2dates().setVisible(true);
            }
        });
    }

    
    
    
    public long days()
    {
        
    DateTimeFormatter formatter=DateTimeFormatter.ofPattern("dd/MM/yyyy");
     
        //1
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
            String date_1 = sdf.format(jDateChooser1.getDate());
             //2
            
            SimpleDateFormat sdf1=new SimpleDateFormat("dd/MM/yyyy");
            String date_2 = sdf1.format(jDateChooser2.getDate());
            
            
            LocalDate date1 =LocalDate.parse(date_1,formatter);
            LocalDate date2 =LocalDate.parse(date_2,formatter);
            
            long daysBetween=ChronoUnit.DAYS.between(date1, date2);
            
            return daysBetween;
            
    
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    // End of variables declaration//GEN-END:variables
}
