/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mortgage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author prime
 */    

public class signin extends javax.swing.JFrame {
    
    
    String sno;
    String True="true";
    String Mod="yes";
    String selected;
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    
    

    /**
     * Creates new form signin
     */
    public signin() {
         con=sql_connection.ConnectDB();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        type = new javax.swing.JComboBox<>();
        jPasswordField1 = new javax.swing.JPasswordField();
        button1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(220, 240, 240));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setBackground(new java.awt.Color(220, 240, 240));
        jInternalFrame1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 15, true));
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(102, 102, 102));
        label1.setFont(new java.awt.Font("Constantia", 1, 48)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Yash Jewellers");
        jInternalFrame1.getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 390, 100));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 102, 102));
        label2.setText("Password");
        jInternalFrame1.getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 280, 80));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        label3.setForeground(new java.awt.Color(0, 102, 102));
        label3.setText("ID");
        jInternalFrame1.getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 280, 80));

        type.setBackground(new java.awt.Color(204, 204, 204));
        type.setFont(new java.awt.Font("Myanmar Text", 0, 24)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User", "Developer" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 290, 40));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPasswordField1.setText("admin1234");
        jInternalFrame1.getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 280, 30));

        button1.setBackground(new java.awt.Color(153, 153, 153));
        button1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Login");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        jInternalFrame1.getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 120, 30));

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked

        
        
        
        
        
        
        
        
        
        new welcome().setVisible(true);
                super.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseClicked

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed

        
        selected=type.getSelectedItem().toString();
        System.out.println(selected);
    }//GEN-LAST:event_typeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signin().setVisible(true);
            }
        });
    }
    
    
    
    
    
    public void Date_difference()
    {
        
  //      int day_difference=0;
        int i=1;        ///Starting point
        
        
        DateTimeFormatter formatter=DateTimeFormatter.ofPattern("dd/MM/yyyy");
         
        //1 st date
             String current_date = new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime());
           LocalDate system_date =LocalDate.parse(current_date,formatter);
          
        
        String db_date="";
         
              
         
         //getting max serial
         
         try{
            String serial_query="select max(serial) from lent";
            pst=con.prepareStatement(serial_query);
             rs=pst.executeQuery();    
             sno=rs.getString("max(serial)");
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
         
         
         //getting date from tabel
         while(i<=Integer.valueOf(sno))
         {
             LocalDate database_date =LocalDate.parse(date_extractor(i),formatter);
             
             long daysBetween=ChronoUnit.DAYS.between(database_date, system_date);
             
             
             
             if(daysBetween<10)
             {
                  
                 String SQL="update  lent set expiry='True' , mod='yes' where serial ='"+i+"' ";
                 
             try{
           
           pst=con.prepareStatement(SQL);
            
             pst.execute();
             System.out.println(daysBetween);
             
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
                 
             }
             
             else
             {
                 String SQL="update  lent set expiry='False' , mod='yes' where serial ='"+i+"' ";
                 
                 try{
           
           pst=con.prepareStatement(SQL);
            
             pst.execute();
             System.out.println(daysBetween);
             
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
                 System.out.println("else");
                 
             }
             i++;
             
         }
        
         
         
    }
    
    
    
    
    
    
    
    
    
    
    
public String date_extractor(int serial)
{
    
     int s=serial;
     String extracted_date="";
    try {
             String test="Select date from lent where serial='"+s+"'";
            pst=con.prepareStatement(test);
             rs=pst.executeQuery();
             
             if(rs.next())
             {
                 extracted_date=rs.getString("date");
                 
              
             }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    
    
    
    return extracted_date;
    
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPasswordField jPasswordField1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
