/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mortgage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author prime
 */
public class updation extends javax.swing.JFrame {
    
    
     Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;


    /**
     * Creates new form updation
     */
    public updation() {
        con=sql_connection.ConnectDB();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        textField4 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        textField1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label5 = new java.awt.Label();
        button1 = new java.awt.Button();
        textField5 = new java.awt.TextField();
        label6 = new java.awt.Label();
        button3 = new java.awt.Button();
        button2 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Cambria Math", 0, 36)); // NOI18N
        label1.setText("Update / Modification Page");
        jPanel2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 550, 80));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textField4.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel3.add(textField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 210, 30));

        textField2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel3.add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 210, 30));

        textField1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel3.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 210, 30));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Palatino Linotype", 1, 32)); // NOI18N
        label2.setForeground(new java.awt.Color(51, 0, 0));
        label2.setText("Number");
        jPanel3.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 290, 40));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Palatino Linotype", 1, 32)); // NOI18N
        label3.setForeground(new java.awt.Color(51, 0, 0));
        label3.setText("Returned Amount");
        jPanel3.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 290, 50));

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setFont(new java.awt.Font("Palatino Linotype", 1, 32)); // NOI18N
        label5.setForeground(new java.awt.Color(51, 0, 0));
        label5.setText("Name");
        jPanel3.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 290, 40));

        button1.setBackground(new java.awt.Color(0, 204, 255));
        button1.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        button1.setLabel("Find");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        jPanel3.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 170, 40));

        textField5.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel3.add(textField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 210, 30));

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setFont(new java.awt.Font("Palatino Linotype", 1, 32)); // NOI18N
        label6.setForeground(new java.awt.Color(51, 0, 0));
        label6.setText("Serial Number");
        jPanel3.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 290, 40));

        button3.setBackground(new java.awt.Color(0, 204, 255));
        button3.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        button3.setLabel("Update");
        button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button3MouseClicked(evt);
            }
        });
        jPanel3.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 170, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 700, 630));

        button2.setBackground(new java.awt.Color(204, 255, 153));
        button2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        button2.setLabel("Go back");
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 40));

        jTable1.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 690, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked
                
        new welcome().setVisible(true);
                super.dispose();     
    }//GEN-LAST:event_button2MouseClicked

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
      
        try{
        String sql="Select * from lent where serial =?";
        
                    pst=con.prepareStatement(sql);
                    pst.setString(1, textField5.getText());
                    rs=pst.executeQuery();
                   
                        System.out.println(rs);
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                    
                    
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
        }
                         // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseClicked

    private void button3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MouseClicked
         
        
        String SQL="update  lent set name='"+textField4.getText()+"' , mod='"+textField2.getText()+"' , returned_amount='"+textField1.getText()+"' where serial ='"+textField5.getText()+"' ";
                 
             try{
           
           pst=con.prepareStatement(SQL);
            
             pst.execute();
            
             
 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
            
            
        }
             
             try{
        String sql="Select * from lent where serial =?";
        
                    pst=con.prepareStatement(sql);
                    pst.setString(1, textField5.getText());
                    rs=pst.executeQuery();
                   
                        System.out.println(rs);
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                    
                    
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
        }
    }//GEN-LAST:event_button3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    // End of variables declaration//GEN-END:variables
}
